import type { Metadata } from 'next'
import { services } from '@/content/services'
import { site } from '@/content/site'
import { team } from '@/content/team'

/** The share picture generated by app/opengraph-image.tsx. */
export const DEFAULT_SHARE_IMAGE = '/opengraph-image'

type PageSeo = { title: string; description: string; path: string; image?: string }

/**
 * Metadata for one page: its canonical address and a large share card. Pages set
 * all of it explicitly, because a page's openGraph replaces the layout's whole
 * openGraph object, image included.
 */
export function pageMetadata({ title, description, path, image = DEFAULT_SHARE_IMAGE }: PageSeo): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: 'website',
      locale: site.locale,
      siteName: site.name,
      title,
      description,
      url: path,
      images: [image],
    },
    twitter: { card: 'summary_large_image', title, description, images: [image] },
  }
}

/** Who IndiWeb is, for search engines (schema.org), shown on the home page. */
export function organizationJsonLd() {
  return {
    '@context': 'https://schema.org',
    '@type': 'ProfessionalService',
    name: site.name,
    url: site.url,
    email: site.email,
    description: site.description,
    image: `${site.url}${DEFAULT_SHARE_IMAGE}`,
    founder: team.map((member) => ({ '@type': 'Person', name: member.name })),
    knowsAbout: services.map((service) => service.title),
    areaServed: ['CZ', 'SK'],
    availableLanguage: ['cs', 'sk'],
  }
}
